"use client";

import React, { useState, KeyboardEvent } from "react";
import { Label } from "../../atoms/label";

/**
 * Interface that defines the properties of the Accordion component
 *
 * @param title The title to be displayed in the accordion header
 * @param content The content to be displayed when the accordion is expanded
 * @param isOpen Determines if the accordion is initially open
 * @param className Additional CSS classes to customize the accordion
 */
export interface AccordionProps {
  title: string;
  content: string;
  isOpen?: boolean;
  className?: string;
}

/**
 * Accordion component that displays a collapsible element with title and content
 * Manages the expansion state and user interaction
 *
 * @param title The title to be displayed in the accordion header
 * @param content The content to be displayed when the accordion is expanded
 * @param isOpen Determines if the accordion is initially open (default: false)
 * @param className Additional CSS classes to customize the accordion (default: "")
 */
export const Accordion: React.FC<AccordionProps> = ({
  title,
  content,
  isOpen = false,
  className = "",
}) => {
  const [isManuallyExpanded, setIsManuallyExpanded] = useState(false);
  const isExpanded = isManuallyExpanded || isOpen;

  /**
   * Method that toggles the expansion state of the accordion
   */
  const toggleAccordion = () => {
    setIsManuallyExpanded(!isManuallyExpanded);
  };

  /**
   * Handles keyboard events to enable accessibility
   * Allows expanding/collapsing the accordion using Enter and Space keys
   *
   * @param e The keyboard event generated by user interaction
   */
  const handleKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
    if (e.key === "Enter") {
      toggleAccordion();
    } else if (e.key === " ") {
      e.preventDefault();
      toggleAccordion();
    }
  };

  return (
    <div
      className={`w-full rounded-lg overflow-hidden bg-[#E7F1FF] ${className}`}
    >
      <div
        onClick={toggleAccordion}
        onKeyDown={handleKeyDown}
        tabIndex={0}
        role="button"
        aria-expanded={isExpanded}
        className="flex items-center justify-between cursor-pointer transition-colors outline-none"
      >
        <div className="flex items-center">
          <span className="mr-2 text-xl">{isExpanded ? "−" : "+"}</span>
          <Label
            text={title}
            font="font-sfProDisplay"
            textColor="text-blue-dark"
            className="font-bold"
          />
        </div>
      </div>
      <div
        className={`overflow-hidden transition-all duration-300 ease-in-out ${
          isExpanded ? "max-h-96" : "max-h-0"
        }`}
      >
        <Label
          text={content}
          font="font-sfProDisplay"
          textColor="text-blue-dark"
        />
      </div>
    </div>
  );
};
